CREATE TABLE mars_weather (
   id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   season VARCHAR(255) NOT NULL,
   northSeason VARCHAR(255) NOT NULL,
   southSeason VARCHAR(255) NOT NULL,
   averageTemp FLOAT NOT NULL,
   atmosphericPressure FLOAT NOT NULL,
   marsWindSpeed FLOAT NOT NULL,
   reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
