CREATE TABLE earth_weather (
   id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   overall VARCHAR(255) NOT NULL,
   description VARCHAR(255) NOT NULL,
   wind_speed FLOAT NOT NULL,
   sunrise INT NOT NULL,
   sunset INT NOT NULL,
   reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
